---
title: "microbiome_fluoxetine"
author: "Gabriel Melhado"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages
pacman::p_load(readr, here, dplyr, tidyr, stringr, tibble, phyloseq, vegan, ggplot2, lme4, lmerTest)

```

```{r}
# Read VSEARCH TSV (ignores QIIME2 '#q2:types' line)
data <- read_tsv(here("data", "vsearch_merged_freq_tax.tsv"),
comment = "#",
show_col_types = FALSE
)


# Rename sample columns: remove ".fastq" suffix
# (only affects columns after the taxonomy fields)
names(data) <- names(data) %>%
str_replace("\\.fastq$", "")

```

```{r}
# Sanity checks and identification of sample columns
stopifnot(all(c("id", "Taxon", "Consensus") %in% names(data)))

sample_cols <- setdiff(
names(data),
c("id", "Sequence", "Taxon", "Consensus")
)

```

```{r}
# Build ASV count matrix (taxa = rows, samples = columns)
otu_mat <- data %>%
select(id, all_of(sample_cols)) %>%
column_to_rownames("id") %>%
as.matrix()


otu <- otu_table(otu_mat, taxa_are_rows = TRUE)

# Build taxonomy table
## Taxonomy format: d__Bacteria;p__...;c__...;...

tax_df <- data %>%
select(id, Taxon) %>%
mutate(Taxon = str_replace_all(Taxon, ";\\s*", ";")) %>%
separate(
col = Taxon,
into = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"),
sep = ";",
fill = "right",
extra = "drop"
) %>%
mutate(across(Kingdom:Species, ~ na_if(.x, "Unassigned"))) %>%
column_to_rownames("id")


tax <- tax_table(as.matrix(tax_df))

```

```{r}
# Read and prepare metadata
meta <- read_csv(here("data", "experimental_data.csv"))

meta <- meta %>%
mutate(sample_id = as.character(sample_id)) %>%
column_to_rownames("sample_id")
                 
sam <- sample_data(meta)

```

```{r}
# Create phyloseq object
ps <- phyloseq(otu, tax, sam)

# Check sample matching
samples_in_otu <- sample_names(ps)
samples_in_meta <- rownames(meta)


missing_in_meta <- setdiff(samples_in_otu, samples_in_meta)
missing_in_otu <- setdiff(samples_in_meta, samples_in_otu)


cat("Samples in OTU but not in metadata:", length(missing_in_meta), "\n")
cat("Samples in metadata but not in OTU:", length(missing_in_otu), "\n")

ps <- prune_samples(sample_names(ps) %in% rownames(meta), ps)

ps

```


```{r}
## Rarefy your phyloseq object to depth = 15667
# It subsamples without replacement so every sample has the same library size (15667 reads), making alpha diversity comparable across samples.
# Depth -> file rarefaction_depth_suggested
set.seed(123)

DEPTH <- 15667

ps_rarefied <- rarefy_even_depth(
  ps,
  sample.size = DEPTH,
  rngseed = 123,
  replace = FALSE,
  verbose = TRUE
)

# number of samples in each object
nsamples(ps)
nsamples(ps_rarefied)

# Confirm library sizes are all equal after rarefaction
summary(sample_sums(ps_rarefied))

# List dropped smaples
dropped <- setdiff(sample_names(ps), sample_names(ps_rarefied))
length(dropped)
dropped

# Samples per treatment after drop
meta_micro <- meta[sample_names(ps_rarefied), ]

table(meta$treatment)
table(meta_micro$treatment)

```

```{r}
## Alpha diversity
# Compute diversity metrics
alpha_df <- estimate_richness(
  ps_rarefied,
  measures = c("Observed", "Shannon")
)

alpha_df <- alpha_df %>%
  rownames_to_column("sample_id") %>%
  left_join(
    meta_micro %>% rownames_to_column("sample_id"),
    by = "sample_id"
  )

# Remove the leading x
alpha_df <- alpha_df %>%
  mutate(sample_id = str_remove(sample_id, "^X"))

# Re-join metadata
alpha_df <- alpha_df %>%
  select(-batch, -tank, -treatment, -mucus_collection, -body_mass, -body_length) %>%
  left_join(
    meta_micro %>% rownames_to_column("sample_id"),
    by = "sample_id"
  )

head(alpha_df)

# Sanity check
stopifnot(!any(is.na(alpha_df$treatment)))

```

```{r}
# Treatment as factor
alpha_df <- alpha_df %>%
  mutate(
    treatment = factor(treatment, levels = c("C", "L", "H")),
    tank = factor(tank),
    batch = factor(batch)
  )

```

```{r}
# Visualisation
# Shannon diversity plot
ggplot(alpha_df, aes(x = treatment, y = Shannon)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.15, alpha = 0.6) +
  theme_bw() +
  labs(x = "Treatment", y = "Shannon diversity")

# Richness plot
ggplot(alpha_df, aes(x = treatment, y = Observed)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.15, alpha = 0.6) +
  theme_bw() +
  labs(x = "Treatment", y = "Observed ASVs")

```

```{r}
## Model alpha diversity (with tank as a random effect)
# Shannon
m_shannon <- lmer(
  Shannon ~ treatment + (1 | tank),
  data = alpha_df
)

summary(m_shannon)
anova(m_shannon)

```

```{r}
# Richness
m_obs <- lmer(
  Observed ~ treatment + (1 | tank),
  data = alpha_df
)

summary(m_obs)
anova(m_obs)

```

```{r}
## Beta diversity (community composition)
# Compute Bray-Curtis distance matrix
bray_dist <- phyloseq::distance(
  ps_rarefied,
  method = "bray"
)

bray_dist

```

```{r}
# Beta diviersity visualisation (PCoA)
ordu <- ordinate(
  ps_rarefied,
  method = "PCoA",
  distance = bray_dist
)

pcoa_plot <- plot_ordination(
  ps_rarefied,
  ordu,
  color = "treatment"
) +
  geom_point(size = 3, alpha = 0.8) +
  theme_bw() +
  labs(
    title = "PCoA (Bray–Curtis)",
    color = "Treatment"
  )

pcoa_plot
```

```{r}
## PERMANOVA
meta_perm <- meta_micro[sample_names(ps_rarefied), ]

stopifnot(identical(rownames(meta_perm), labels(bray_dist)))

# Treatment only
set.seed(123)

perm_treat <- adonis2(
  bray_dist ~ treatment,
  data = meta_perm,
  permutations = 999
)

perm_treat


# Treatment + tank
set.seed(123)

perm_treat_tank <- adonis2(
  bray_dist ~ treatment,
  data = meta_perm,
  permutations = 999,
  strata = meta_perm$tank
)

perm_treat_tank

```

```{r}
# Check homogeneity of dispersion
disp <- betadisper(bray_dist, meta_perm$treatment)

anova(disp)
permutest(disp, permutations = 999)

boxplot(disp, ylab = "Distance to group centroid")

```

